version: '3'

services:
  mongo:
    container_name: mongo-container
    image: mongo:6.0.3-focal
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  
  api:
    container_name: api-container
    build: .    
    image: signup-signin
    restart: always
    command: npm start
    volumes:
      - ./dist:/api/dist
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/api-db
      - JWT_SECRET=e8U-=!kd

    