version: '3'

services:
  mongo:
    container_name: mongo-container
    image: mongo:6.0.3-focal
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  
  api:
    container_name: api-container
    image: node:16
    working_dir: /usr/src/api
    restart: always
    command: bash -c "npm install --omit=dev && npm run debug"
    volumes:
      - ./dist/:/usr/src/api/dist/
      - ./package.json:/usr/src/api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    depends_on:
      - mongo
    env_file:
    - ./.env

